obstacle_range: 3.0
raytrace_range: 3.5
# obstacle_range: 2.5
# raytrace_range: 3.0
# footprint: [[-0.105, -0.105], [-0.105, 0.105], [0.041, 0.105], [0.041, -0.105]]
#robot_radius: 0.105
robot_radius: 0.3
inflation_radius: 0.8
cost_scaling_factor: 3.0
map_type: costmap
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true}