  GlobalPlanner:
    allow_unkown: false
    default_tolerance: 0.0
    visualize_potential: true
    use_dijkstra: false # false=A star
    use_quadratic: true
    use_grid_path: false
    old_navfn_behavior: false



