#base_global_planner: "navfn/NavfnROS" #"global_planner/GlobalPlanner"
base_local_planner: "dwa_local_planner/DWAPlannerROS"
shutdown_costmaps: false
controller_frequency: 10.0
controller_patience: 15.0
planner_patience: 5.0
conservative_reset_dist: 3.0
planner_frequency: 0.0
oscillation_timeout: 0.0
oscillation_distance: 0.2
visualize_potential: true

